don't allow selection of info messages
deltachat/deltachat-ios pull request #1614
Opened 2022-06-21 15:46 UTC by cyBerta

fixes #1610 

* also restricts cell selection handling to those cells implementing SelectableCell protocol

2022-06-22 08:18 UTC, r10s requested changes
i think, info-messages should be multi-selectable as other message so that a user can delete them together with other messages 

this is how it works on android, desktop does not have multi-select but allows deletion of a single info-message.

for forwarding: android hides the option if one of the message is an info-message, desktop allows forwarding. as info-messags are not forwarded as such (only text is forwarded), i think, the latter is also fine - and probably easier to do.

(of course daymakers and n-new-message markers cannot be deleted)

2022-06-22 08:25 UTC, cyBerta commented
ok, I'll allow mutli-selecting info messages then, if they don't have the message  ID of  a daymarker or new message marker.

2022-06-22 13:24 UTC, r10s commented
as core allows forwarding info-messages, i added a test to make sure, they're not forwarded as info-messages but only as text: https://github.com/deltachat/deltachat-core-rust/pull/3446 there is also some reasoning why forwarding info-messages may be not-so-good, however :) let's discuss there and leave this open until it is resolved there :)

2022-06-24 10:21 UTC, r10s approved these changes

2022-06-24 10:21 UTC, merged