show number of selected chats in title
deltachat/deltachat-ios pull request #1623
Opened 2022-06-24 19:38 UTC by r10s

this bit is missing somehow, having the wording "selected" in the title also underlines that one is in "select" mode.

<img width=320 src=https://user-images.githubusercontent.com/9800740/175655975-cc0152a1-5291-47ba-aac9-1403226dd156.PNG>

i was also thinking about saying "N Chats Selected" in the title bar, however, this will get easily to wide in translations, so, i decided for the short variation. also, that way the string can be reused in similar views ;)

2022-06-25 16:13 UTC, cyBerta commented
nice idea

2022-06-25 16:22 UTC, cyBerta commented
in order to make sure, we handle the title correctly in all possible states (forwarding, archive, multi-select, normal -> connection states)  I would prefer if the handling would happen within updateTitle(). It is a little bit easier to follow, and a little bit less likely to introduce regressions later on.

2022-06-25 16:23 UTC, cyBerta requested changes
in order to ensure we handle the title correctly in all possible states (forwarding, archive, multi-select, normal -> connection states) I would prefer if the handling would happen within updateTitle(). It is a little bit easier to follow, and a little bit less likely to introduce regressions later on.

2022-06-27 14:47 UTC, r10s commented
> in order to ensure we handle the title correctly in all possible states (forwarding, archive, multi-select, normal -> connection states) I would prefer if the handling would happen within updateTitle(). It is a little bit easier to follow, and a little bit less likely to introduce regressions later on.

i would also prefer that, however, i hestiated as it was unclear to me if `setLeftBarButton()` etc. are idempotent when applying the same object over and over (which would happen if we leave the existing logic as is).

having a closer look at https://developer.apple.com/documentation/uikit/uinavigationitem/1624954-setleftbarbutton this discusses only applying the same object to different views, however, one can probably assume that applying the same object to the same view is okay as well. 

@cyBerta do we have experiences with that in otherview? or what is your stance on this?

2022-06-29 23:35 UTC, cyBerta commented
it should do nothing, e.g. regarding animations, if the same object is applied to the the same UIBarButton.

2022-07-01 11:32 UTC, r10s commented
@cyBerta i added a commit, now all title changes are done in updateTitle(). the function is still a bit confusing wrt state changes etc, however, if we want to clean up further there, that should go to another pr (i tried, but that would make review of this pr much harder :)

2022-07-02 09:22 UTC, merged

2022-07-04 12:04 UTC, cyBerta commented
great, thanks for this nice improvement