[WIP] Webxdc selector
deltachat/deltachat-ios pull request #1668
Opened 2022-08-11 14:23 UTC by cyBerta

2022-08-16 11:05 UTC, r10s reviewed
some quick functionality check: when there are no apps:
- an assert is logged `deltachat-ios[71734:885763] [Assert] negative or zero item sizes are not supported in the flow layout`
- a wrong placeholder message is shown ("Images and videos shared in this chat will appear here.")

2022-08-19 12:18 UTC, r10s approved these changes
no blockers, however, maybe target the easy things already in this pr, then we can merge that to test it ourselves together with the webxdc-icon-to-homescreen :)

2022-08-21 11:58 UTC, cyBerta commented
> * an assert is logged `deltachat-ios[71734:885763] [Assert] negative or zero item sizes are not supported in the flow layout`

I still need to fix that. It seems that there's a bug with prefetching items.

2022-08-22 12:13 UTC, r10s requested changes
the recent changes are great!

however, a bug sneaked in: when you try to attach a webxdc using "Apps / Files" or just the old "Files" entry, things do not work, the app is shown as an error then:

<img width=320 src=https://user-images.githubusercontent.com/9800740/185918448-973c0757-f1c5-4ea0-a306-5a69d5f320c6.jpg>

2022-08-22 12:14 UTC, r10s commented on deltachat-ios/en.lproj/Localizable.strings
> +"webxdc_empty_hint" = "Webxdc apps you have received or sent will appear here. You can tap on files to select downloaded apps.";
```suggestion
"webxdc_empty_hint" = "Received or sent apps will appear here. Tap \"Files\" to select downloaded apps.";
```

2022-08-22 12:16 UTC, r10s commented on deltachat-ios/en.lproj/Localizable.strings
> +"webxdc_empty_hint" = "Webxdc apps you have received or sent will appear here. You can tap on files to select downloaded apps.";
ah, that one is generated, should go to untranslated.xml

2022-08-22 12:17 UTC, r10s commented on scripts/untranslated.xml
> +    <string name ="webxdc_empty_hint">Webxdc apps you have received or sent will appear here. You can tap on files to select downloaded apps.</string>
```suggestion
    <string name ="webxdc_empty_hint">Received or sent apps will appear here. Tap &quot;Files&quot; to select downloaded apps.</string>
```

2022-08-22 18:07 UTC, cyBerta commented
> the recent changes are great!
> 
> however, a bug sneaked in: when you try to attach a webxdc using "Apps / Files" or just the old "Files" entry, things do not work, the app is shown as an error then:
> 
> <img alt="" width="320" src="https://user-images.githubusercontent.com/9800740/185918448-973c0757-f1c5-4ea0-a306-5a69d5f320c6.jpg">
> 
> worse: even the preview of eg. PDFs are missing now. there seems to be sth. broken with attaching files in general :)

Does the issue persist for you with the latest version? It doesn't happen to me. I suspect you were trying with ios 15.X right?

2022-08-22 21:35 UTC, r10s commented
for the title: great, this is much better. 

two minors:

- can we have a bigger font? ideally the same size and weight as used when selecting "Files" in icon mode? (list mode is maybe a bit too big)
- i'd add a bit more padding between the cells, maybe the font height. that way, it is also visually clearer where the title belongs to (as the padding between icon and title is unchanged)

2022-08-23 01:51 UTC, merged